### ISSUE TITLE
Add tests and CI

### ISSUE THREAD

**Issue by weswigham** [JRJurman/PowerLS#1]
Refer to https://github.com/chrisbenti/PS-Config for an example.

**Comment by JRJurman** [comment]
I leave that as an exercise for the inquisitive reader!

**Comment by chrisbenti** [comment]
https://github.com/its-not-batch/PSPowerline is probably a better model to work off of. That treats the module as a proper package.

**Comment by weswigham** [comment]
Well, you have CI now... maybe you should add a status badge to the readme and more tests I guess?
