### ISSUE TITLE
Repository not found in PowerShell 6/7 NuGet

### ISSUE THREAD

**Issue by emmet-m** [JRJurman/PowerLS#10]
Hi there,

Would it be possible to create a NuGet repository for PowerShell 6/7? Having PsGet's `install-module` and the system one is a little strange.

Thanks very much!

**Comment by JRJurman** [comment]
I'll be honest, it's been a very long time since I worked on this project, and even then I wasn't that familiar with the PowerShell ecosystem. If you have any instructions on how to do what you're requesting, I'd be happy to follow whatever instructions and try to get it working for your setup (if it's not super complicated).

**Comment by emmet-m** [comment]
Sure! I'm not all too familiar with PowerShell either, but I noticed things seemed to have changed a lot in the newer PowerShell versions (6/7).

PowerShell 6/7 now comes in with a builtin `Install-Module` command that isn't part of PSGet. This command looks in repositories for a module, where the default repository is [PowerShell Gallery](https://www.powershellgallery.com/). You can register with a Microsoft account and publish your own module up there with `Publish-Module`. Clicking on the 'Publish' tab will give you more info. From there, you can install that module with the builtin `Install-Module`

P.s. Thanks so much for this project, I invest a lot of time in making my shell work for me and I've been using this for over 2 years now!

**Comment by JRJurman** [comment]
Thanks for the links! I'll work on this this weekend and see if I can get all the metadata and everything in here to get it published :D

**Comment by mika76** [comment]
Came here to say just this 😄

**Comment by JRJurman** [comment]
Sorry for the delay on any updates here. I did make an account, and made a module, however I seem to be getting an error on trying to publish the module... In the process of debugging the issue...

**Comment by JRJurman** [comment]
Okay, so I tried picking this up again, but without any real luck , and I can't even appear to get the local `import-module` working. To be honest, I'm using Windows OS less frequently, and even when I am, I'm using git bash. 

If someone would like to pick up this project, feel free to fork it, and I will update the README to direct users to a forked version that is published and maintained.
