### ISSUE TITLE
Looking for new Maintainer

### ISSUE THREAD

**Issue by JRJurman** [JRJurman/PowerLS#12]
I realize that I'm unable to run this locally, and to be honest, I'm using Windows OS less frequently, and even when I am, I'm using git bash. I realize that in #10 people would appreciate this package being more available (and potentially with real feature improvements), but without the ability to test or run those changes, I feel like it would be disingenuous to have the project under my name.  

If someone would like to pick up this project, I would be willing to transfer ownership or point the README to a maintained fork.

**Comment by rashil2000** [comment]
@JRJurman Hi, not sure if you're still maintaining this but I'd be glad to pick this up to publish it to PSGallery :)

**Comment by JRJurman** [comment]
@rashil2000 that would be awesome! I can add you as a contributor or transfer ownership, whatever you need to publish it 😄

**Comment by rashil2000** [comment]
Hi @JRJurman ! Sorry for the late reply, but I wouldn't be able to take this up. 

By the way, a PS module by the name PowerColorLS already exists on PSGallery which provides much much more functionality and is actively maintained.

**Comment by JRJurman** [comment]
Oh, I didn't realize that! I'll update the readme to point to that project
