### ISSUE TITLE
OT: what prompt are you using?

### ISSUE THREAD

**Issue by toburger** [JRJurman/PowerLS#5]
sorry, this isn't related to PowerLS but I like the prompt you are using in the screenshot of your readme.

**Comment by weswigham** [comment]
[ConEmu](https://github.com/Maximus5/ConEmu)

**Comment by toburger** [comment]
any special settings that configures the "arrow" behind the path? 
![image](https://cloud.githubusercontent.com/assets/728782/12264487/709e4632-b937-11e5-9385-218fa5e4ce37.png)

**Comment by weswigham** [comment]
[PSPowerline](https://github.com/its-not-batch/PSPowerline) (also with [posh-git](https://github.com/dahlbyk/posh-git))

**Comment by weswigham** [comment]
Using the one of the patched [fonts](https://gist.github.com/qrush/1595572).

**Comment by toburger** [comment]
nice! thx a lot!
